export const SYSTEM_PROFILE_DEFINITIONS = [
  {
    name: 'Super Admin',
    slug: 'SUPER_ADMIN',
    description: 'Acesso total a todos os modulos e configuracoes do EloSystem.',
    type: 'SYSTEM',
    isSystem: true,
    permissions: ['*'],
  },
  {
    name: 'Admin',
    slug: 'ADMIN',
    description:
      'Gestao administrativa ampla com acesso aos modulos operacionais e de usuarios.',
    type: 'SYSTEM',
    isSystem: true,
    permissions: [
      'dashboard.read',
      'users.read',
      'users.create',
      'users.update',
      'users.status',
      'users.reset_password',
      'users.assign_profiles',
      'profiles.read',
      'profiles.create',
      'profiles.update',
      'profiles.assign',
      'permissions.read',
      'audit.read',
      'audit.export',
      'integrations.read',
      'integrations.update',
      'integrations.manage',
      'integrations.sync',
      'integrations.logs.read',
      'storage.read',
      'storage.upload',
      'storage.manage',
      'settings.read',
      'settings.update',
      'settings.company',
      'settings.payroll',
      'settings.performance',
      'settings.security',
      'settings.notifications',
      'security.read',
      'security.manage',
      'security.sessions.manage',
      'security.mfa.manage',
      'users.security.read',
      'employees.read',
      'employees.create',
      'employees.update',
      'employees.delete',
      'documents.read',
      'documents.create',
      'documents.update',
      'documents.delete',
      'documents.approve',
      'warnings.read',
      'warnings.create',
      'warnings.update',
      'suspensions.read',
      'suspensions.create',
      'leave.read',
      'leave.create',
      'vacations.read',
      'vacations.create',
      'onboarding.read',
      'onboarding.update',
      'uniforms.read',
      'uniforms.update',
      'benefits.read',
      'benefits.update',
      'payroll.read',
      'payroll.process',
      'payroll.sync_from_time',
      'payroll.review_auto_entries',
      'payroll.close',
      'payroll.reopen',
      'payroll.movement.read',
      'payroll.movement.create',
      'payroll.movement.update',
      'payroll.movement.delete',
      'payroll.payslip.read',
      'payroll.payslip.export',
      'payroll.event.read',
      'payroll.events.create',
      'payroll.events.update',
      'payroll.events.status',
      'payroll.charges.read',
      'payroll.charges.export',
      'time.read',
      'time.import',
      'time.review',
      'time.bank_hours.read',
      'time.export',
      'work_schedules.read',
      'work_schedules.create',
      'work_schedules.update',
      'work_schedules.publish',
      'work_schedules.cancel',
      'work_schedules.assign',
      'trainings.read',
      'trainings.files.read',
      'trainings.create',
      'trainings.update',
      'performance.read',
      'performance.export',
      'performance.pdf.read',
      'performance.evaluate',
      'performance.feedback',
      'performance.external_feedback',
      'performance.development_plan',
      'recruitment.read',
      'recruitment.create',
      'recruitment.update',
      'preadmission.read',
      'preadmission.create',
      'preadmission.update',
      'calendar.read',
      'reports.read',
      'reports.export_excel',
      'reports.export_pdf',
      'reports.audit',
      'reports.payroll',
      'reports.hr',
    ],
  },
  {
    name: 'RH',
    slug: 'RH',
    description:
      'Operacao de RH com foco em pessoas, documentos, admissao e ocorrencias.',
    type: 'SYSTEM',
    isSystem: true,
    permissions: [
      'dashboard.read',
      'users.read',
      'audit.read',
      'integrations.read',
      'integrations.update',
      'integrations.manage',
      'integrations.sync',
      'integrations.logs.read',
      'storage.read',
      'storage.upload',
      'settings.read',
      'settings.company',
      'settings.payroll',
      'settings.performance',
      'settings.notifications',
      'security.read',
      'security.sessions.manage',
      'users.security.read',
      'employees.read',
      'employees.create',
      'employees.update',
      'documents.read',
      'documents.create',
      'documents.update',
      'documents.approve',
      'warnings.read',
      'warnings.create',
      'warnings.update',
      'suspensions.read',
      'suspensions.create',
      'leave.read',
      'leave.create',
      'vacations.read',
      'vacations.create',
      'onboarding.read',
      'onboarding.update',
      'uniforms.read',
      'uniforms.update',
      'benefits.read',
      'benefits.update',
      'payroll.read',
      'payroll.process',
      'payroll.sync_from_time',
      'payroll.review_auto_entries',
      'payroll.close',
      'payroll.reopen',
      'payroll.movement.read',
      'payroll.movement.create',
      'payroll.movement.update',
      'payroll.movement.delete',
      'payroll.payslip.read',
      'payroll.payslip.export',
      'payroll.event.read',
      'payroll.events.create',
      'payroll.events.update',
      'payroll.events.status',
      'payroll.charges.read',
      'payroll.charges.export',
      'time.read',
      'time.import',
      'time.review',
      'time.bank_hours.read',
      'time.export',
      'work_schedules.read',
      'work_schedules.create',
      'work_schedules.update',
      'work_schedules.publish',
      'work_schedules.cancel',
      'work_schedules.assign',
      'trainings.read',
      'trainings.files.read',
      'trainings.create',
      'trainings.update',
      'performance.read',
      'performance.export',
      'performance.pdf.read',
      'performance.evaluate',
      'performance.feedback',
      'performance.external_feedback',
      'performance.development_plan',
      'recruitment.read',
      'recruitment.create',
      'recruitment.update',
      'preadmission.read',
      'preadmission.create',
      'preadmission.update',
      'calendar.read',
      'reports.read',
      'reports.export_excel',
      'reports.export_pdf',
      'reports.audit',
      'reports.payroll',
      'reports.hr',
    ],
  },
  {
    name: 'Gestor',
    slug: 'GESTOR',
    description:
      'Leitura gerencial com acompanhamento de equipe, ocorrencias e paineis.',
    type: 'SYSTEM',
    isSystem: true,
    permissions: [
      'dashboard.read',
      'employees.read',
      'documents.read',
      'warnings.read',
      'leave.read',
      'vacations.read',
      'onboarding.read',
      'time.read',
      'time.bank_hours.read',
      'work_schedules.read',
      'work_schedules.create',
      'work_schedules.update',
      'work_schedules.publish',
      'work_schedules.assign',
      'benefits.read',
      'trainings.read',
      'trainings.files.read',
      'performance.read',
      'performance.export',
      'performance.pdf.read',
      'performance.feedback',
      'recruitment.read',
      'calendar.read',
      'reports.read',
      'reports.export_excel',
      'reports.export_pdf',
      'security.read',
    ],
  },
  {
    name: 'Visualizador',
    slug: 'VISUALIZADOR',
    description: 'Acesso somente leitura aos paineis e modulos permitidos.',
    type: 'SYSTEM',
    isSystem: true,
    permissions: ['dashboard.read', 'employees.read', 'calendar.read', 'reports.read'],
  },
];

export const PERMISSION_DEFINITIONS = [
  {
    module: 'dashboard',
    action: 'read',
    key: 'dashboard.read',
    description: 'Visualizar o dashboard estrategico.',
  },
  {
    module: 'users',
    action: 'read',
    key: 'users.read',
    description: 'Listar e visualizar usuarios.',
  },
  {
    module: 'users',
    action: 'create',
    key: 'users.create',
    description: 'Criar novos usuarios de acesso.',
  },
  {
    module: 'users',
    action: 'update',
    key: 'users.update',
    description: 'Editar dados cadastrais de usuarios.',
  },
  {
    module: 'users',
    action: 'status',
    key: 'users.status',
    description: 'Ativar, inativar ou bloquear usuarios.',
  },
  {
    module: 'users',
    action: 'reset_password',
    key: 'users.reset_password',
    description: 'Redefinir senha de usuarios.',
  },
  {
    module: 'users',
    action: 'assign_profiles',
    key: 'users.assign_profiles',
    description: 'Vincular perfis a usuarios.',
  },
  {
    module: 'profiles',
    action: 'read',
    key: 'profiles.read',
    description: 'Visualizar perfis e permissoes.',
  },
  {
    module: 'profiles',
    action: 'create',
    key: 'profiles.create',
    description: 'Criar perfis de acesso.',
  },
  {
    module: 'profiles',
    action: 'update',
    key: 'profiles.update',
    description: 'Editar perfis de acesso.',
  },
  {
    module: 'profiles',
    action: 'assign',
    key: 'profiles.assign',
    description: 'Gerenciar permissoes e vinculos dos perfis.',
  },
  {
    module: 'permissions',
    action: 'read',
    key: 'permissions.read',
    description: 'Consultar catalogo de permissoes.',
  },
  {
    module: 'audit',
    action: 'read',
    key: 'audit.read',
    description: 'Visualizar a central de auditoria e rastreabilidade.',
  },
  {
    module: 'audit',
    action: 'export',
    key: 'audit.export',
    description: 'Exportar trilhas e relatorios de auditoria.',
  },
  {
    module: 'integrations',
    action: 'read',
    key: 'integrations.read',
    description: 'Visualizar o hub administrativo de integracoes do EloSystem.',
  },
  {
    module: 'integrations',
    action: 'update',
    key: 'integrations.update',
    description: 'Atualizar configuracoes administrativas das integracoes.',
  },
  {
    module: 'integrations',
    action: 'manage',
    key: 'integrations.manage',
    description: 'Gerenciar providers, ativacao e postura operacional das integracoes.',
  },
  {
    module: 'integrations',
    action: 'sync',
    key: 'integrations.sync',
    description: 'Executar testes, sincronizacoes e operacoes administrativas das integracoes.',
  },
  {
    module: 'integrations',
    action: 'logs.read',
    key: 'integrations.logs.read',
    description: 'Consultar logs, historico e trilha operacional das integracoes.',
  },
  {
    module: 'storage',
    action: 'read',
    key: 'storage.read',
    description: 'Visualizar configuracoes e metadados do storage corporativo.',
  },
  {
    module: 'storage',
    action: 'upload',
    key: 'storage.upload',
    description: 'Enviar e sincronizar arquivos com o storage corporativo.',
  },
  {
    module: 'storage',
    action: 'manage',
    key: 'storage.manage',
    description: 'Gerenciar provedores, pastas-raiz e sincronizacao documental.',
  },
  {
    module: 'settings',
    action: 'read',
    key: 'settings.read',
    description: 'Visualizar o centro administrativo de configuracoes do sistema.',
  },
  {
    module: 'settings',
    action: 'update',
    key: 'settings.update',
    description: 'Editar parametros administrativos e configuracoes futuras do sistema.',
  },
  {
    module: 'settings',
    action: 'company',
    key: 'settings.company',
    description: 'Gerenciar dados institucionais e unidades da empresa.',
  },
  {
    module: 'settings',
    action: 'payroll',
    key: 'settings.payroll',
    description: 'Gerenciar parametros da folha e regras de Departamento Pessoal.',
  },
  {
    module: 'settings',
    action: 'performance',
    key: 'settings.performance',
    description: 'Gerenciar pesos e criterios configuraveis do modulo Desempenho.',
  },
  {
    module: 'settings',
    action: 'security',
    key: 'settings.security',
    description: 'Gerenciar politicas de seguranca e sessao do sistema.',
  },
  {
    module: 'settings',
    action: 'notifications',
    key: 'settings.notifications',
    description: 'Gerenciar alertas, notificacoes e comunicacoes do sistema.',
  },
  {
    module: 'security',
    action: 'read',
    key: 'security.read',
    description: 'Visualizar paineis, historico e configuracoes de seguranca de autenticacao.',
  },
  {
    module: 'security',
    action: 'manage',
    key: 'security.manage',
    description: 'Gerenciar politicas, bloqueios e postura de seguranca do EloSystem.',
  },
  {
    module: 'security',
    action: 'sessions.manage',
    key: 'security.sessions.manage',
    description: 'Revogar sessoes, encerrar acessos e administrar historico de sessao.',
  },
  {
    module: 'security',
    action: 'mfa.manage',
    key: 'security.mfa.manage',
    description: 'Ativar, desativar e exigir autenticacao em duas etapas.',
  },
  {
    module: 'users',
    action: 'security.read',
    key: 'users.security.read',
    description: 'Visualizar historico de login, MFA e estado de seguranca por usuario.',
  },
  {
    module: 'employees',
    action: 'read',
    key: 'employees.read',
    description: 'Visualizar colaboradores.',
  },
  {
    module: 'employees',
    action: 'create',
    key: 'employees.create',
    description: 'Criar colaboradores.',
  },
  {
    module: 'employees',
    action: 'update',
    key: 'employees.update',
    description: 'Editar colaboradores.',
  },
  {
    module: 'employees',
    action: 'delete',
    key: 'employees.delete',
    description: 'Excluir colaboradores.',
  },
  {
    module: 'documents',
    action: 'read',
    key: 'documents.read',
    description: 'Visualizar documentos e anexos.',
  },
  {
    module: 'documents',
    action: 'create',
    key: 'documents.create',
    description: 'Cadastrar documentos.',
  },
  {
    module: 'documents',
    action: 'update',
    key: 'documents.update',
    description: 'Editar documentos.',
  },
  {
    module: 'documents',
    action: 'delete',
    key: 'documents.delete',
    description: 'Excluir documentos.',
  },
  {
    module: 'documents',
    action: 'approve',
    key: 'documents.approve',
    description: 'Aprovar documentos e pendencias.',
  },
  {
    module: 'warnings',
    action: 'read',
    key: 'warnings.read',
    description: 'Visualizar advertencias.',
  },
  {
    module: 'warnings',
    action: 'create',
    key: 'warnings.create',
    description: 'Criar advertencias.',
  },
  {
    module: 'warnings',
    action: 'update',
    key: 'warnings.update',
    description: 'Editar advertencias.',
  },
  {
    module: 'suspensions',
    action: 'read',
    key: 'suspensions.read',
    description: 'Visualizar suspensoes.',
  },
  {
    module: 'suspensions',
    action: 'create',
    key: 'suspensions.create',
    description: 'Registrar suspensoes.',
  },
  {
    module: 'leave',
    action: 'read',
    key: 'leave.read',
    description: 'Visualizar afastamentos.',
  },
  {
    module: 'leave',
    action: 'create',
    key: 'leave.create',
    description: 'Registrar afastamentos.',
  },
  {
    module: 'vacations',
    action: 'read',
    key: 'vacations.read',
    description: 'Visualizar ferias.',
  },
  {
    module: 'vacations',
    action: 'create',
    key: 'vacations.create',
    description: 'Gerenciar ferias.',
  },
  {
    module: 'onboarding',
    action: 'read',
    key: 'onboarding.read',
    description: 'Visualizar onboardings.',
  },
  {
    module: 'onboarding',
    action: 'update',
    key: 'onboarding.update',
    description: 'Atualizar onboardings e integracoes.',
  },
  {
    module: 'uniforms',
    action: 'read',
    key: 'uniforms.read',
    description: 'Visualizar fardamento e estoque.',
  },
  {
    module: 'uniforms',
    action: 'update',
    key: 'uniforms.update',
    description: 'Atualizar fardamento e estoque.',
  },
  {
    module: 'benefits',
    action: 'read',
    key: 'benefits.read',
    description: 'Visualizar beneficios.',
  },
  {
    module: 'benefits',
    action: 'update',
    key: 'benefits.update',
    description: 'Atualizar beneficios.',
  },
  {
    module: 'payroll',
    action: 'read',
    key: 'payroll.read',
    description: 'Visualizar competencias e resultados da folha.',
  },
  {
    module: 'payroll',
    action: 'process',
    key: 'payroll.process',
    description: 'Processar ou reprocessar a competencia da folha.',
  },
  {
    module: 'payroll',
    action: 'sync_from_time',
    key: 'payroll.sync_from_time',
    description: 'Sincronizar dados consolidados da jornada com a competencia da folha.',
  },
  {
    module: 'payroll',
    action: 'review_auto_entries',
    key: 'payroll.review_auto_entries',
    description: 'Revisar lancamentos automaticos gerados pela integracao Jornada -> Folha.',
  },
  {
    module: 'payroll',
    action: 'close',
    key: 'payroll.close',
    description: 'Fechar competencias processadas da folha.',
  },
  {
    module: 'payroll',
    action: 'reopen',
    key: 'payroll.reopen',
    description: 'Reabrir competencias fechadas da folha.',
  },
  {
    module: 'payroll.movement',
    action: 'read',
    key: 'payroll.movement.read',
    description: 'Visualizar lancamentos da folha por colaborador.',
  },
  {
    module: 'payroll.movement',
    action: 'create',
    key: 'payroll.movement.create',
    description: 'Criar lancamentos na competencia da folha.',
  },
  {
    module: 'payroll.movement',
    action: 'update',
    key: 'payroll.movement.update',
    description: 'Editar lancamentos na competencia da folha.',
  },
  {
    module: 'payroll.movement',
    action: 'delete',
    key: 'payroll.movement.delete',
    description: 'Inativar lancamentos da competencia da folha.',
  },
  {
    module: 'payroll',
    action: 'payslip.read',
    key: 'payroll.payslip.read',
    description: 'Visualizar preview de holerite da folha.',
  },
  {
    module: 'payroll',
    action: 'payslip.export',
    key: 'payroll.payslip.export',
    description: 'Exportar ou imprimir holerites da folha.',
  },
  {
    module: 'payroll.event',
    action: 'read',
    key: 'payroll.event.read',
    description: 'Consultar eventos disponiveis para lancamento na folha.',
  },
  {
    module: 'payroll.event',
    action: 'create',
    key: 'payroll.events.create',
    description: 'Criar eventos e rubricas da folha.',
  },
  {
    module: 'payroll.event',
    action: 'update',
    key: 'payroll.events.update',
    description: 'Editar eventos e rubricas da folha.',
  },
  {
    module: 'payroll.event',
    action: 'status',
    key: 'payroll.events.status',
    description: 'Ativar, inativar e duplicar eventos da folha.',
  },
  {
    module: 'payroll.charges',
    action: 'read',
    key: 'payroll.charges.read',
    description: 'Consultar consolidacao de encargos por competencia.',
  },
  {
    module: 'payroll.charges',
    action: 'export',
    key: 'payroll.charges.export',
    description: 'Exportar conferencias e consolidacoes de encargos.',
  },
  {
    module: 'time',
    action: 'read',
    key: 'time.read',
    description: 'Visualizar jornada, consolidacoes e historico de importacoes.',
  },
  {
    module: 'time',
    action: 'import',
    key: 'time.import',
    description: 'Importar relatorios de ponto do MyAhgora, TOTVS ou fontes compativeis.',
  },
  {
    module: 'time',
    action: 'review',
    key: 'time.review',
    description: 'Revisar pendencias, confirmar importacoes e resolver vinculos da jornada.',
  },
  {
    module: 'time.bank_hours',
    action: 'read',
    key: 'time.bank_hours.read',
    description: 'Visualizar saldos e consolidacoes do banco de horas.',
  },
  {
    module: 'time',
    action: 'export',
    key: 'time.export',
    description: 'Exportar consolidacoes da jornada e banco de horas.',
  },
  {
    module: 'work_schedules',
    action: 'read',
    key: 'work_schedules.read',
    description: 'Visualizar o planejamento operacional de escalas.',
  },
  {
    module: 'work_schedules',
    action: 'create',
    key: 'work_schedules.create',
    description: 'Criar novas escalas e planejamentos especiais.',
  },
  {
    module: 'work_schedules',
    action: 'update',
    key: 'work_schedules.update',
    description: 'Editar dados gerais das escalas operacionais.',
  },
  {
    module: 'work_schedules',
    action: 'publish',
    key: 'work_schedules.publish',
    description: 'Publicar escalas para uso operacional.',
  },
  {
    module: 'work_schedules',
    action: 'cancel',
    key: 'work_schedules.cancel',
    description: 'Cancelar ou arquivar escalas com rastreabilidade.',
  },
  {
    module: 'work_schedules',
    action: 'assign',
    key: 'work_schedules.assign',
    description: 'Adicionar, editar e remover colaboradores escalados.',
  },
  {
    module: 'trainings',
    action: 'read',
    key: 'trainings.read',
    description: 'Visualizar treinamentos.',
  },
  {
    module: 'trainings',
    action: 'files.read',
    key: 'trainings.files.read',
    description: 'Visualizar e baixar anexos de certificados e capacitacoes.',
  },
  {
    module: 'trainings',
    action: 'create',
    key: 'trainings.create',
    description: 'Criar treinamentos e vinculos.',
  },
  {
    module: 'trainings',
    action: 'update',
    key: 'trainings.update',
    description: 'Atualizar treinamentos e certificados.',
  },
  {
    module: 'performance',
    action: 'read',
    key: 'performance.read',
    description: 'Visualizar indicadores, historico e painel de desempenho.',
  },
  {
    module: 'performance',
    action: 'export',
    key: 'performance.export',
    description: 'Gerar documentos oficiais e exportacoes do modulo Desempenho.',
  },
  {
    module: 'performance',
    action: 'pdf.read',
    key: 'performance.pdf.read',
    description: 'Visualizar e baixar PDFs oficiais de avaliacao de desempenho.',
  },
  {
    module: 'performance',
    action: 'evaluate',
    key: 'performance.evaluate',
    description: 'Registrar avaliacoes gerenciais de desempenho.',
  },
  {
    module: 'performance',
    action: 'feedback',
    key: 'performance.feedback',
    description: 'Registrar feedback interno de colegas para desempenho.',
  },
  {
    module: 'performance',
    action: 'external_feedback',
    key: 'performance.external_feedback',
    description: 'Registrar feedback externo de clientes ou empresas atendidas.',
  },
  {
    module: 'performance',
    action: 'development_plan',
    key: 'performance.development_plan',
    description: 'Gerenciar plano de desenvolvimento ligado ao desempenho.',
  },
  {
    module: 'recruitment',
    action: 'read',
    key: 'recruitment.read',
    description: 'Visualizar recrutamento e selecao.',
  },
  {
    module: 'recruitment',
    action: 'create',
    key: 'recruitment.create',
    description: 'Criar candidatos e etapas.',
  },
  {
    module: 'recruitment',
    action: 'update',
    key: 'recruitment.update',
    description: 'Atualizar pipeline de candidatos.',
  },
  {
    module: 'preadmission',
    action: 'read',
    key: 'preadmission.read',
    description: 'Visualizar pre-admissoes.',
  },
  {
    module: 'preadmission',
    action: 'create',
    key: 'preadmission.create',
    description: 'Criar pre-admissoes.',
  },
  {
    module: 'preadmission',
    action: 'update',
    key: 'preadmission.update',
    description: 'Atualizar pre-admissoes e aprovacoes.',
  },
  {
    module: 'calendar',
    action: 'read',
    key: 'calendar.read',
    description: 'Visualizar agenda e proximos eventos.',
  },
  {
    module: 'reports',
    action: 'read',
    key: 'reports.read',
    description: 'Visualizar a central de relatorios e seus previews.',
  },
  {
    module: 'reports',
    action: 'export_excel',
    key: 'reports.export_excel',
    description: 'Exportar relatorios executivos em Excel.',
  },
  {
    module: 'reports',
    action: 'export_pdf',
    key: 'reports.export_pdf',
    description: 'Exportar relatorios executivos em PDF.',
  },
  {
    module: 'reports',
    action: 'audit',
    key: 'reports.audit',
    description: 'Acessar relatorios sensiveis de auditoria e rastreabilidade.',
  },
  {
    module: 'reports',
    action: 'payroll',
    key: 'reports.payroll',
    description: 'Acessar relatorios financeiros de folha, holerites e encargos.',
  },
  {
    module: 'reports',
    action: 'hr',
    key: 'reports.hr',
    description: 'Acessar relatorios operacionais de RH, jornada e documentacao.',
  },
];

export const SYSTEM_PROFILE_SLUGS = SYSTEM_PROFILE_DEFINITIONS.map(
  (profile) => profile.slug
);

export const DEFAULT_PROFILE_SLUG_BY_ROLE = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN: 'ADMIN',
  RH: 'RH',
  GESTOR: 'GESTOR',
  VISUALIZADOR: 'VISUALIZADOR',
};

export const ALL_PERMISSION_KEYS = PERMISSION_DEFINITIONS.map(
  (permission) => permission.key
);
